swagger:
  mapErrorsToJson: true
  docEndpoints:
    raw: /api/server/v1/json
    ui: /api/server/v1

  defaultPipe: null
  fittingsDirs: [ middlewares ]
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:

    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ api/mocks ]
      controllersDirs: [ api/controllers ]

    _swagger_validate:
      name: swagger_validator
      validateResponse: true

    # pipe for all swagger-node controllers
    swagger_controllers:
      - cors
      - swagger_params_parser
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - log.request.middleware
      - _router

    # # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw